### ISSUE TITLE
Crypto module

### ISSUE THREAD

**Issue by romulofranco** [PawanOsman/sydney-ai#3]
First, I tried to redirect the app to use crypto-js, but without success..
After I use this snippet code:
 ```
extendWebpack(cfg) {
        cfg.plugins.push(new NodePolyfillPlugin({
          include aliases: ['crypto','stream']
        }));
      },
```
No success. The error that I am facing:

```
TypeError: crypto__WEBPACK_IMPORTED_MODULE_0__.randomUUID is not a function
    at Conversation.resetConversation (conversation.js:79:43)
    at new Conversation (conversation.js:24:1)
    at ChatBot.addConversation (chatbot.js:14:1)
    at ChatBot.getConversation (chatbot.js:22:1)
    at ChatBot.ask (chatbot.js:30:1)
    at sendMessageBot (ChatPage.vue:114:29)
    at enviarMensaje (ChatPage.vue:105:9)
    at runtime-dom.esm-bundler.js:1469:1
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:1)
```
I saw many workaround for Quasar Framework, but none of them I got the solution for that.

Thanks in advance.

**Comment by PawanOsman** [comment]
you don't need to install it, its built-in package
make sure you are using nodejs 18+,
looks like your compiler couldn't compile it
